## Exploración inicial del dataset de ventas

Se carga el dataset para revisar su estructura y contenido

In [6]:
import pandas as pd

sales = pd.read_csv("../data/raw/sales_data_sample.csv",encoding="latin-1")
sales.info()
sales.info()

sales.columns

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   str
 6   STATUS            2823 non-null   str
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   str
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   str
 13  CUSTOMERNAME      2823 non-null   str
 14  PHONE             2823 non-null   str
 15  ADDRESSLINE1      2823 non-null   str
 16  ADDRESSLINE2      302 non-null    str
 17  CITY              2823 non-null   str
 18  STATE             1337 non-null   str
 19  POSTALCODE        2747 non-null   str
 20  COUNTRY           2823 non-null   str
 21  TERRITORY         1749 non-null   str
 22  CONTACTLASTNAME   2823 non-null   str
 23  CONTACTFIRSTNAME  2823 non-null   str
 24  DEALSIZE          2823 non-null   str
dtypes: float64(2), int64(7), str(16)
memory usage: 551.5 KB
<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   str
 6   STATUS            2823 non-null   str
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   str
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   str
 13  CUSTOMERNAME      2823 non-null   str
 14  PHONE             2823 non-null   str
 15  ADDRESSLINE1      2823 non-null   str
 16  ADDRESSLINE2      302 non-null    str
 17  CITY              2823 non-null   str
 18  STATE             1337 non-null   str
 19  POSTALCODE        2747 non-null   str
 20  COUNTRY           2823 non-null   str
 21  TERRITORY         1749 non-null   str
 22  CONTACTLASTNAME   2823 non-null   str
 23  CONTACTFIRSTNAME  2823 non-null   str
 24  DEALSIZE          2823 non-null   str
dtypes: float64(2), int64(7), str(16)
memory usage: 551.5 KB

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='str')

In [7]:
for i, col in enumerate(sales.columns):
    print(i, col)

0 ORDERNUMBER
1 QUANTITYORDERED
2 PRICEEACH
3 ORDERLINENUMBER
4 SALES
5 ORDERDATE
6 STATUS
7 QTR_ID
8 MONTH_ID
9 YEAR_ID
10 PRODUCTLINE
11 MSRP
12 PRODUCTCODE
13 CUSTOMERNAME
14 PHONE
15 ADDRESSLINE1
16 ADDRESSLINE2
17 CITY
18 STATE
19 POSTALCODE
20 COUNTRY
21 TERRITORY
22 CONTACTLASTNAME
23 CONTACTFIRSTNAME
24 DEALSIZE

In [9]:
sales['ORDERDATE'] = pd.to_datetime(sales['ORDERDATE'])

In [10]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   datetime64[us]
 6   STATUS            2823 non-null   str
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   str
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   str
 13  CUSTOMERNAME      2823 non-null   str
 14  PHONE             2823 non-null   str
 15  ADDRESSLINE1      2823 non-null   str
 16  ADDRESSLINE2      302 non-null    str
 17  CITY              2823 non-null   str
 18  STATE             1337 non-null   str
 19  POSTALCODE        2747 non-null   str
 20  COUNTRY           2823 non-null   str
 21  TERRITORY         1749 non-null   str
 22  CONTACTLASTNAME   2823 non-null   str
 23  CONTACTFIRSTNAME  2823 non-null   str
 24  DEALSIZE          2823 non-null   str
dtypes: datetime64[us](1), float64(2), int64(7), str(15)
memory usage: 551.5 KB

In [11]:
sales['calculated_sales'] = sales['QUANTITYORDERED'] * sales['PRICEEACH']

In [12]:
sales['difference'] = sales['SALES'] - sales['calculated_sales']

In [13]:
sales[['SALES', 'calculated_sales', 'difference']].head()

     SALES  calculated_sales    difference
0  2871.00           2871.00  0.000000e+00
1  2765.90           2765.90  4.547474e-13
2  3884.34           3884.34  4.547474e-13
3  3746.70           3746.70 -4.547474e-13
4  5205.27           4900.00  3.052700e+02

In [14]:
sales[sales['difference'] != 0]

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,calculated_sales,difference
1,10121,34,81.35,5,2765.90,2003-05-07,Shipped,2,5,2003,...,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small,2765.90,4.547474e-13
2,10134,41,94.74,2,3884.34,2003-07-01,Shipped,3,7,2003,...,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium,3884.34,4.547474e-13
3,10145,45,83.26,6,3746.70,2003-08-25,Shipped,3,8,2003,...,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium,3746.70,-4.547474e-13
4,10159,49,100.00,14,5205.27,2003-10-10,Shipped,4,10,2003,...,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium,4900.00,3.052700e+02
5,10168,36,96.66,1,3479.76,2003-10-28,Shipped,4,10,2003,...,Burlingame,CA,94217,USA,NaN,Hirano,Juri,Medium,3479.76,4.547474e-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2816,10327,37,86.74,4,3209.38,2004-11-10,Resolved,4,11,2004,...,Kobenhavn,NaN,1734,Denmark,EMEA,Petersen,Jytte,Medium,3209.38,4.547474e-13
2818,10350,20,100.00,15,2244.40,2004-12-02,Shipped,4,12,2004,...,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small,2000.00,2.444000e+02
2819,10373,29,100.00,1,3978.51,2005-01-31,Shipped,1,1,2005,...,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium,2900.00,1.078510e+03
2820,10386,43,100.00,4,5417.57,2005-03-01,Resolved,1,3,2005,...,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium,4300.00,1.117570e+03
2822,10414,47,65.52,9,3079.44,2005-05-06,On Hold,2,5,2005,...,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium,3079.44,4.547474e-13

In [15]:
sales[sales['difference'].abs() > 1].shape

(1303, 27)

## Validación de la métrica de ventas

Se realizó una validación comparando el valor de ventas reportado (`SALES`) con el cálculo basado en la cantidad y el precio unitario.

Durante este análisis se identificaron diferencias en varios registros. Algunas de estas diferencias son mínimas y se deben a temas de precisión decimal, sin embargo, también se encontraron diferencias más significativas.

Esto sugiere que el valor de ventas puede estar influenciado por factores adicionales como descuentos, impuestos u otros ajustes que no están explícitos en el dataset.

Por esta razón, se decidió mantener la columna `SALES` como fuente principal para el análisis, ya que representa el valor final de la transacción.

In [16]:
cols = [
    'ORDERNUMBER',
    'ORDERDATE',
    'PRODUCTCODE',
    'QUANTITYORDERED',
    'PRICEEACH',
    'SALES',
    'COUNTRY'
]

sales_clean = sales[cols]

In [17]:
sales_clean.head()
sales_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ORDERNUMBER      2823 non-null   int64
 1   ORDERDATE        2823 non-null   datetime64[us]
 2   PRODUCTCODE      2823 non-null   str
 3   QUANTITYORDERED  2823 non-null   int64
 4   PRICEEACH        2823 non-null   float64
 5   SALES            2823 non-null   float64
 6   COUNTRY          2823 non-null   str
dtypes: datetime64[us](1), float64(2), int64(2), str(2)
memory usage: 154.5 KB

## Selección de variables relevantes

Se realizó una selección de las columnas más relevantes para el análisis, enfocándose en aquellas que aportan valor para entender el comportamiento de las ventas.

Se excluyeron variables relacionadas con información de contacto y direcciones, ya que no son necesarias para responder las preguntas de negocio planteadas.

Las variables seleccionadas permiten analizar ventas, productos y ubicación geográfica de manera eficiente.

In [18]:
productos = sales[['PRODUCTCODE']].drop_duplicates().reset_index(drop=True)

## Eliminacón de datos repetidos

ELinimé con drop_duplicates, los productos repetidos y resetié el index para que quedaran ordenados

In [19]:
productos['producto_id'] = range(1, len(productos) + 1)

In [20]:
productos = productos.rename(columns={
    'producto_id': 'product_id'
})

In [21]:
productos = productos.rename(columns={
    'PRODUCTCODE': 'product_name'
})

## Construcción de la tabla de productos

A partir del dataset de ventas, se generó una tabla de productos utilizando los valores únicos de la columna `PRODUCTCODE`.

Se creó un identificador numérico (`product_id`) para cada producto, con el fin de facilitar la relación entre tablas y mejorar la estructura del modelo de datos.

Esta tabla permite separar la información de productos de las transacciones, siguiendo un enfoque más organizado y escalable.

In [23]:
sales = sales.merge(productos, left_on='PRODUCTCODE', right_on='product_name', how='left')

## Integración de productos con ventas

deicíd integrar la tabla de ventas y la tabla de productos utilizando el código del producto como llave de relación.

Esto permitió incorporar el identificador numérico (`product_id`) en la tabla de ventas, facilitando la construcción del modelo analítico y futuras relaciones entre datasets.

In [24]:
len(productos)

109

In [25]:
sales_countries = set(sales['COUNTRY'].unique())
sales_countries

{'Australia',
 'Austria',
 'Belgium',
 'Canada',
 'Denmark',
 'Finland',
 'France',
 'Germany',
 'Ireland',
 'Italy',
 'Japan',
 'Norway',
 'Philippines',
 'Singapore',
 'Spain',
 'Sweden',
 'Switzerland',
 'UK',
 'USA'}

## Generación de clientes desde API

In [30]:
import requests
import pandas as pd

url = "https://randomuser.me/api/?results=200"

response = requests.get(url)
data = response.json()

customers = []

for user in data['results']:
    customers.append({
        "customer_name": user['name']['first'] + " " + user['name']['last'],
        "city": user['location']['city'],
        "country": user['location']['country']
    })

df_customers = pd.DataFrame(customers)

df_customers['customer_id'] = range(1, len(df_customers) + 1)

In [31]:
customers_countries = set(df_customers['country'].unique())
customers_countries

{'Australia',
 'Brazil',
 'Canada',
 'Denmark',
 'Finland',
 'France',
 'Germany',
 'India',
 'Iran',
 'Ireland',
 'Mexico',
 'Netherlands',
 'New Zealand',
 'Norway',
 'Serbia',
 'Spain',
 'Switzerland',
 'Turkey',
 'Ukraine',
 'United Kingdom',
 'United States'}

In [ ]:
sales_countries = set(sales['COUNTRY'].unique())
customers_countries = set(df_customers['country'].unique())

sales_countries - customers_countries
customers_countries - sales_countries

In [36]:
sales_countries - customers_countries

{'Austria',
 'Belgium',
 'Italy',
 'Japan',
 'Philippines',
 'Singapore',
 'Sweden',
 'UK',
 'USA'}

In [35]:
customers_countries - sales_countries

{'Brazil',
 'India',
 'Iran',
 'Mexico',
 'Netherlands',
 'New Zealand',
 'Serbia',
 'Turkey',
 'Ukraine',
 'United Kingdom',
 'United States'}

In [34]:
mapping = {
    "USA": "United States",
    "UK": "United Kingdom"
}

sales['COUNTRY'] = sales['COUNTRY'].replace(mapping)

In [37]:
customers_countries - sales_countries

{'Brazil',
 'India',
 'Iran',
 'Mexico',
 'Netherlands',
 'New Zealand',
 'Serbia',
 'Turkey',
 'Ukraine',
 'United Kingdom',
 'United States'}

In [38]:
sales_countries - customers_countries

{'Austria',
 'Belgium',
 'Italy',
 'Japan',
 'Philippines',
 'Singapore',
 'Sweden',
 'UK',
 'USA'}

In [39]:
sales['COUNTRY'] = sales['COUNTRY'].str.strip()

In [40]:
mapping = {
    "USA": "United States",
    "UK": "United Kingdom"
}

sales['COUNTRY'] = sales['COUNTRY'].replace(mapping)

In [41]:
sales['COUNTRY'].unique()

<StringArray>
[ 'United States',         'France',         'Norway',      'Australia',
        'Finland',        'Austria', 'United Kingdom',          'Spain',
         'Sweden',      'Singapore',         'Canada',          'Japan',
          'Italy',        'Denmark',        'Belgium',    'Philippines',
        'Germany',    'Switzerland',        'Ireland']
Length: 19, dtype: str

In [42]:
sales_countries = set(sales['COUNTRY'].unique())
customers_countries = set(df_customers['country'].unique())

sales_countries - customers_countries

{'Austria', 'Belgium', 'Italy', 'Japan', 'Philippines', 'Singapore', 'Sweden'}

## Limpieza y normalización de países

Se realizó una limpieza de la columna `COUNTRY` para eliminar posibles espacios en blanco y asegurar consistencia en los valores.

Posteriormente, se aplicó una normalización de nombres para unificar representaciones de países como "USA" y "UK" a sus equivalentes completos.

Esto permitió mejorar la calidad de los datos y facilitar la integración entre datasets.

In [43]:
import numpy as np

sales['customer_id'] = np.random.choice(
    df_customers['customer_id'],
    size=len(sales)
)

In [44]:
sales.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,calculated_sales,difference,product_name,product_id,customer_id
0,10107,30,95.70,2,2871.00,2003-02-24,Shipped,1,2,2003,...,United States,NaN,Yu,Kwai,Small,2871.00,0.000000e+00,S10_1678,1,141
1,10121,34,81.35,5,2765.90,2003-05-07,Shipped,2,5,2003,...,France,EMEA,Henriot,Paul,Small,2765.90,4.547474e-13,S10_1678,1,184
2,10134,41,94.74,2,3884.34,2003-07-01,Shipped,3,7,2003,...,France,EMEA,Da Cunha,Daniel,Medium,3884.34,4.547474e-13,S10_1678,1,136
3,10145,45,83.26,6,3746.70,2003-08-25,Shipped,3,8,2003,...,United States,NaN,Young,Julie,Medium,3746.70,-4.547474e-13,S10_1678,1,148
4,10159,49,100.00,14,5205.27,2003-10-10,Shipped,4,10,2003,...,United States,NaN,Brown,Julie,Medium,4900.00,3.052700e+02,S10_1678,1,43

## Asignación de clientes a ventas

Después de normalizar los nombres de los países, se identificó que no existe una correspondencia completa entre los países de los datasets de ventas y clientes.

Debido a esta limitación, se optó por asignar clientes de forma aleatoria a cada venta.

Esta decisión permite mantener la estructura del modelo sin asumir relaciones incorrectas entre clientes y ubicaciones geográficas.

In [45]:
cols = [
    'ORDERNUMBER',
    'ORDERDATE',
    'product_id',
    'customer_id',
    'QUANTITYORDERED',
    'PRICEEACH',
    'SALES',
    'COUNTRY'
]

sales_final = sales[cols].copy()

In [46]:
sales_final = sales_final.rename(columns={
    'ORDERNUMBER': 'order_number',
    'ORDERDATE': 'order_date',
    'QUANTITYORDERED': 'quantity',
    'PRICEEACH': 'price_each',
    'SALES': 'sales',
    'COUNTRY': 'country'
})

In [47]:
products_final = productos.copy()

In [48]:
customers_final = df_customers.copy()

In [49]:
sales_final.to_csv("../data/processed/sales.csv", index=False)

In [52]:
import requests

response = requests.get("https://restcountries.com/v3.1/all")
countries_data = response.json()

regions_list = []
for c in countries_data:
    regions_list.append({
        "country_name": c.get("name", {}).get("common", ""),
        "region": c.get("region", ""),
        "subregion": c.get("subregion", ""),
        "continent": c.get("continents", [""])[0]
    })

df_regions = pd.DataFrame(regions_list)
df_regions.head()

AttributeError: 'str' object has no attribute 'get'

In [54]:
response = requests.get("https://restcountries.com/v3.1/all?fields=name,region,subregion,continents")
print(response.status_code)
countries_data = response.json()
print(countries_data[0])

200
{'name': {'common': 'Ivory Coast', 'official': "Republic of Côte d'Ivoire", 'nativeName': {'fra': {'official': "République de Côte d'Ivoire", 'common': "Côte d'Ivoire"}}}, 'region': 'Africa', 'subregion': 'Western Africa', 'continents': ['Africa']}

In [55]:
regions_list = []
for c in countries_data:
    regions_list.append({
        "country": c["name"]["common"],
        "region": c.get("region", ""),
        "subregion": c.get("subregion", ""),
        "continent": c["continents"][0]
    })

df_regions = pd.DataFrame(regions_list)

# Relacionar con ventas
sales_final = sales_final.merge(
    df_regions[["country", "region", "subregion", "continent"]],
    on="country",
    how="left"
)

# Verificar nulls (países que no hicieron match)
print("Sin match:", sales_final[sales_final["region"].isna()]["country"].unique())

Sin match: <StringArray>
[]
Length: 0, dtype: str

In [56]:
# Crear dimensión regions
regions_final = sales_final[["country", "region", "subregion", "continent"]].drop_duplicates().reset_index(drop=True)
regions_final.insert(0, "region_id", regions_final.index + 1)

# Agregar region_id a sales_final
sales_final = sales_final.merge(regions_final[["region_id", "country"]], on="country", how="left")

# Guardar los 4 CSVs
regions_final.to_csv("../data/processed/regions.csv", index=False)
sales_final.to_csv("../data/processed/sales.csv", index=False)

print(f"✅ {len(regions_final)} regiones")
print(f"✅ sales_final columnas: {list(sales_final.columns)}")
print(regions_final)

✅ 19 regiones
✅ sales_final columnas: ['order_number', 'order_date', 'product_id', 'customer_id', 'quantity', 'price_each', 'sales', 'country', 'region', 'subregion', 'continent', 'region_id']
    region_id         country    region                  subregion  \
0           1   United States  Americas              North America
1           2          France    Europe             Western Europe
2           3          Norway    Europe            Northern Europe
3           4       Australia   Oceania  Australia and New Zealand
4           5         Finland    Europe            Northern Europe
5           6         Austria    Europe             Central Europe
6           7  United Kingdom    Europe            Northern Europe
7           8           Spain    Europe            Southern Europe
8           9          Sweden    Europe            Northern Europe
9          10       Singapore      Asia         South-Eastern Asia
10         11          Canada  Americas              North America
11         12           Japan      Asia               Eastern Asia
12         13           Italy    Europe            Southern Europe
13         14         Denmark    Europe            Northern Europe
14         15         Belgium    Europe             Western Europe
15         16     Philippines      Asia         South-Eastern Asia
16         17         Germany    Europe             Western Europe
17         18     Switzerland    Europe             Western Europe
18         19         Ireland    Europe            Northern Europe

        continent
0   North America
1          Europe
2          Europe
3         Oceania
4          Europe
5          Europe
6          Europe
7          Europe
8          Europe
9            Asia
10  North America
11           Asia
12         Europe
13         Europe
14         Europe
15           Asia
16         Europe
17         Europe
18         Europe

In [ ]:
# Dimensión tiempo extraída de order_date
time_final = sales_final[["order_date"]].drop_duplicates().reset_index(drop=True)
time_final.insert(0, "time_id", time_final.index + 1)

time_final["year"]      = pd.to_datetime(time_final["order_date"]).dt.year
time_final["month"]     = pd.to_datetime(time_final["order_date"]).dt.month
time_final["month_name"]= pd.to_datetime(time_final["order_date"]).dt.strftime("%B")
time_final["quarter"]   = pd.to_datetime(time_final["order_date"]).dt.quarter
time_final["day"]       = pd.to_datetime(time_final["order_date"]).dt.day
time_final["weekday"]   = pd.to_datetime(time_final["order_date"]).dt.strftime("%A")

time_final.to_csv("../data/processed/time.csv", index=False)
print(f"✅ {len(time_final)} fechas únicas")
print(time_final.head())

✅ 252 fechas únicas
   time_id order_date  year  month month_name  quarter  day    weekday
0        1 2003-02-24  2003      2   February        1   24     Monday
1        2 2003-05-07  2003      5        May        2    7  Wednesday
2        3 2003-07-01  2003      7       July        3    1    Tuesday
3        4 2003-08-25  2003      8     August        3   25     Monday
4        5 2003-10-10  2003     10    October        4   10     Friday

In [58]:
sales_final = sales_final.merge(time_final[["time_id", "order_date"]], on="order_date", how="left")
sales_final.to_csv("../data/processed/sales.csv", index=False)
print(list(sales_final.columns))

['order_number', 'order_date', 'product_id', 'customer_id', 'quantity', 'price_each', 'sales', 'country', 'region', 'subregion', 'continent', 'region_id', 'time_id']

In [59]:
# Quitar order_date y country (ya están en dimensiones)
cols_sales = [
    "order_number",
    "time_id",
    "product_id",
    "customer_id",
    "region_id",
    "quantity",
    "price_each",
    "sales"
]

sales_final = sales_final[cols_sales]
sales_final.to_csv("../data/processed/sales.csv", index=False)

print(list(sales_final.columns))
print(sales_final.head())

['order_number', 'time_id', 'product_id', 'customer_id', 'region_id', 'quantity', 'price_each', 'sales']
   order_number  time_id  product_id  customer_id  region_id  quantity  \
0         10107        1           1          141          1        30
1         10121        2           1          184          2        34
2         10134        3           1          136          2        41
3         10145        4           1          148          1        45
4         10159        5           1           43          1        49

   price_each    sales
0       95.70  2871.00
1       81.35  2765.90
2       94.74  3884.34
3       83.26  3746.70
4      100.00  5205.27

In [62]:
time_final = sales_final[["order_date"]].drop_duplicates().reset_index(drop=True)
time_final.insert(0, "time_id", time_final.index + 1)

time_final["year"]       = pd.to_datetime(time_final["order_date"]).dt.year
time_final["month"]      = pd.to_datetime(time_final["order_date"]).dt.month
time_final["month_name"] = pd.to_datetime(time_final["order_date"]).dt.strftime("%B")
time_final["quarter"]    = pd.to_datetime(time_final["order_date"]).dt.quarter
time_final["day"]        = pd.to_datetime(time_final["order_date"]).dt.day

time_final.to_csv("../data/processed/time.csv", index=False)
print(list(time_final.columns))
print(time_final.head())

KeyError: "None of [Index(['order_date'], dtype='str')] are in the [columns]"

In [63]:
print(list(sales_final.columns))
print(list(time_final.columns))

['order_number', 'time_id', 'product_id', 'customer_id', 'region_id', 'quantity', 'price_each', 'sales']
['time_id', 'order_date', 'year', 'month', 'month_name', 'quarter', 'day', 'weekday']

In [64]:
time_final = time_final.drop(columns=["weekday"])
time_final.to_csv("../data/processed/time.csv", index=False)
print(list(time_final.columns))

['time_id', 'order_date', 'year', 'month', 'month_name', 'quarter', 'day']

In [67]:
from dotenv import load_dotenv
from sqlalchemy import create_engine
import os

load_dotenv()

engine = create_engine(
    f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

print("✅ Conexión creada")

✅ Conexión creada

In [69]:
products_final.to_sql("products", engine, if_exists="append", index=False)
customers_final.to_sql("customers", engine, if_exists="append", index=False)
regions_final.to_sql("regions", engine, if_exists="append", index=False)
time_final.to_sql("time", engine, if_exists="append", index=False)
sales_final.to_sql("sales", engine, if_exists="append", index=False)

print("✅ 5 tablas cargadas en PostgreSQL")

DatabaseError: Execution failed on sql 'INSERT INTO products (product_name, product_id) VALUES (:product_name, :product_id)': (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "products_pkey"
DETAIL:  Key (product_id)=(1) already exists.

[SQL: INSERT INTO products (product_name, product_id) VALUES (%(product_name__0)s, %(product_id__0)s), (%(product_name__1)s, %(product_id__1)s), (%(product_name__2)s, %(product_id__2)s), (%(product_name__3)s, %(product_id__3)s), (%(product_name__4)s, %(pro ... 4497 characters truncated ... __106)s), (%(product_name__107)s, %(product_id__107)s), (%(product_name__108)s, %(product_id__108)s)]
[parameters: {'product_name__0': 'S10_1678', 'product_id__0': 1, 'product_name__1': 'S10_1949', 'product_id__1': 2, 'product_name__2': 'S10_2016', 'product_id__2': 3, 'product_name__3': 'S10_4698', 'product_id__3': 4, 'product_name__4': 'S10_4757', 'product_id__4': 5, 'product_name__5': 'S10_4962', 'product_id__5': 6, 'product_name__6': 'S12_1099', 'product_id__6': 7, 'product_name__7': 'S12_1108', 'product_id__7': 8, 'product_name__8': 'S12_1666', 'product_id__8': 9, 'product_name__9': 'S12_2823', 'product_id__9': 10, 'product_name__10': 'S12_3148', 'product_id__10': 11, 'product_name__11': 'S12_3380', 'product_id__11': 12, 'product_name__12': 'S12_3891', 'product_id__12': 13, 'product_name__13': 'S12_3990', 'product_id__13': 14, 'product_name__14': 'S12_4473', 'product_id__14': 15, 'product_name__15': 'S12_4675', 'product_id__15': 16, 'product_name__16': 'S18_1097', 'product_id__16': 17, 'product_name__17': 'S18_1129', 'product_id__17': 18, 'product_name__18': 'S18_1342', 'product_id__18': 19, 'product_name__19': 'S18_1367', 'product_id__19': 20, 'product_name__20': 'S18_1589', 'product_id__20': 21, 'product_name__21': 'S18_1662', 'product_id__21': 22, 'product_name__22': 'S18_1749', 'product_id__22': 23, 'product_name__23': 'S18_1889', 'product_id__23': 24, 'product_name__24': 'S18_1984', 'product_id__24': 25 ... 118 parameters truncated ... 'product_name__84': 'S32_1374', 'product_id__84': 85, 'product_name__85': 'S32_2206', 'product_id__85': 86, 'product_name__86': 'S32_2509', 'product_id__86': 87, 'product_name__87': 'S32_3207', 'product_id__87': 88, 'product_name__88': 'S32_3522', 'product_id__88': 89, 'product_name__89': 'S32_4289', 'product_id__89': 90, 'product_name__90': 'S32_4485', 'product_id__90': 91, 'product_name__91': 'S50_1341', 'product_id__91': 92, 'product_name__92': 'S50_1392', 'product_id__92': 93, 'product_name__93': 'S50_1514', 'product_id__93': 94, 'product_name__94': 'S50_4713', 'product_id__94': 95, 'product_name__95': 'S700_1138', 'product_id__95': 96, 'product_name__96': 'S700_1691', 'product_id__96': 97, 'product_name__97': 'S700_1938', 'product_id__97': 98, 'product_name__98': 'S700_2047', 'product_id__98': 99, 'product_name__99': 'S700_2466', 'product_id__99': 100, 'product_name__100': 'S700_2610', 'product_id__100': 101, 'product_name__101': 'S700_2824', 'product_id__101': 102, 'product_name__102': 'S700_2834', 'product_id__102': 103, 'product_name__103': 'S700_3167', 'product_id__103': 104, 'product_name__104': 'S700_3505', 'product_id__104': 105, 'product_name__105': 'S700_3962', 'product_id__105': 106, 'product_name__106': 'S700_4002', 'product_id__106': 107, 'product_name__107': 'S72_1253', 'product_id__107': 108, 'product_name__108': 'S72_3212', 'product_id__108': 109}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [70]:
# Limpiar tablas en orden inverso (primero la de hechos)
with engine.connect() as conn:
    conn.execute("TRUNCATE TABLE sales, time, regions, customers, products RESTART IDENTITY CASCADE")
    conn.commit()

print("✅ Tablas limpiadas")

ObjectNotExecutableError: Not an executable object: 'TRUNCATE TABLE sales, time, regions, customers, products RESTART IDENTITY CASCADE'

In [71]:
products_final.to_sql("products", engine, if_exists="append", index=False)
customers_final.to_sql("customers", engine, if_exists="append", index=False)
regions_final.to_sql("regions", engine, if_exists="append", index=False)
time_final.to_sql("time", engine, if_exists="append", index=False)
sales_final.to_sql("sales", engine, if_exists="append", index=False)

print("✅ 5 tablas cargadas en PostgreSQL")

✅ 5 tablas cargadas en PostgreSQL

## cargamos las tablas